#pragma once

#include <exception>

class BadRow final : std::exception {};
